// app/layout.tsx
import './globals.css'
import { Karantina } from 'next/font/google'

const karantina = Karantina({
  subsets: ['latin'],
  weight: ['300', '400', '700'], // Use the weights you need
  variable: '--font-karantina',  // Optional: for CSS variable usage
})

export const metadata = {
  title: 'PRAKASH MATHEW',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={karantina.className}>
      <body>{children}</body>
    </html>
  )
}
