import './globals.css'
import { Karantina } from 'next/font/google'

const karantina = Karantina({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-karantina',
})

export const metadata = {
  title: 'Prakash',
  description: 'Generated by Next.js',
  icons: {
    icon: '/prakash.ico', // Or .png/.svg depending on your file
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html style={{scrollBehavior: 'smooth'}} lang="en" className={karantina.variable}>
      <body className="bg-neutral-950 font-karantina">{children}</body>
    </html>
  )
}

